-- Review workflow MVP.
-- This file is a migration proposal only. It was not applied to Supabase in this task.
-- The legacy task_language_reviews, T_State/H_State and satellite-sheet flow remain intact.

alter table public.audio_records
  add column if not exists respondent_key text;

create table if not exists public.annotation_cases (
  id bigint generated by default as identity primary key,
  task_id integer not null references public.final_tasks(id) on delete cascade,
  language text not null check (language in ('台語', '客語')),
  state text not null default '待指派',
  assigned_to text,
  assigned_by text,
  assigned_at timestamptz,
  claim_by text,
  claim_token uuid,
  claim_until timestamptz,
  current_version_no integer not null default 0,
  source_stamp text not null default '',
  legacy_unreviewed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (task_id, language)
);

create table if not exists public.annotation_versions (
  id bigint generated by default as identity primary key,
  case_id bigint not null references public.annotation_cases(id) on delete cascade,
  version_no integer not null,
  version_kind text not null default 'draft' check (version_kind in ('draft', 'final', 'legacy')),
  fields jsonb not null default '{}'::jsonb,
  created_by text not null,
  created_at timestamptz not null default now(),
  unique (case_id, version_no)
);

create table if not exists public.audio_assessments (
  id bigint generated by default as identity primary key,
  task_id integer not null references public.final_tasks(id) on delete cascade,
  language text not null check (language in ('台語', '客語')),
  audio_record_id bigint not null references public.audio_records(id) on delete cascade,
  assessor_account text not null,
  respondent_key text not null,
  decision text not null check (decision in ('可用', '不可用', '待追問')),
  reason text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.proofing_events (
  id bigint generated by default as identity primary key,
  case_id bigint not null references public.annotation_cases(id) on delete cascade,
  action text not null,
  actor_account text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.writeback_jobs (
  id bigint generated by default as identity primary key,
  case_id bigint not null references public.annotation_cases(id) on delete cascade,
  version_id bigint not null references public.annotation_versions(id),
  task_id integer not null references public.final_tasks(id),
  source_id text not null,
  source_table text not null,
  language text not null check (language in ('台語', '客語')),
  version_no integer not null,
  source_stamp text not null default '',
  payload jsonb not null default '{}'::jsonb,
  idempotency_key text not null unique,
  status text not null default 'queued' check (status in ('queued', 'processing', 'retry', 'succeeded', 'failed')),
  attempt_count integer not null default 0,
  last_error text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.writeback_errors (
  id bigint generated by default as identity primary key,
  job_id bigint references public.writeback_jobs(id) on delete set null,
  case_id bigint references public.annotation_cases(id) on delete set null,
  error_code text not null default 'unknown',
  error_message text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists annotation_cases_assignment_idx
  on public.annotation_cases (assigned_to, state);
create index if not exists annotation_cases_claim_idx
  on public.annotation_cases (claim_until);
create index if not exists annotation_versions_case_idx
  on public.annotation_versions (case_id, version_no desc);
create index if not exists audio_assessments_audio_idx
  on public.audio_assessments (audio_record_id, assessor_account, created_at desc);
create index if not exists proofing_events_case_idx
  on public.proofing_events (case_id, created_at desc);
create index if not exists writeback_jobs_status_idx
  on public.writeback_jobs (status, updated_at);

-- Legacy rows remain explicitly unreviewed. Their raw audio is not an assessment.
with source_rows as (
  select uuid, 'third_phase_places'::text as source_table,
         tai_class, hak_class, t_updated_at, h_updated_at,
         t_annotator, h_annotator, taihan, tl1, tl2, tl3, tai_note,
         honzii, hp1, hp2, hp3, h_dialect, hak_note
  from public.third_phase_places
  union all
  select uuid, 'test_places'::text as source_table,
         tai_class, hak_class, t_updated_at, h_updated_at,
         t_annotator, h_annotator, taihan, tl1, tl2, tl3, tai_note,
         honzii, hp1, hp2, hp3, h_dialect, hak_note
  from public.test_places
)
insert into public.annotation_cases (
  task_id, language, state, assigned_to, assigned_by, assigned_at,
  source_stamp, legacy_unreviewed
)
select
  ft.id,
  lang.language,
  'legacy_unreviewed',
  old_review.assigned_to,
  old_review.assigned_by,
  old_review.assigned_at,
  case when lang.language = '台語' then coalesce(src.t_updated_at, '') else coalesce(src.h_updated_at, '') end,
  true
from public.final_tasks ft
join source_rows src
  on src.uuid = ft.source_id and src.source_table = ft.source_table
cross join (values ('台語'::text), ('客語'::text)) as lang(language)
left join public.task_language_reviews old_review
  on old_review.task_id = ft.id and old_review.language = lang.language
on conflict (task_id, language) do nothing;

with source_rows as (
  select uuid, 'third_phase_places'::text as source_table,
         taihan, tl1, tl2, tl3, tai_note, honzii, hp1, hp2, hp3, h_dialect, hak_note
  from public.third_phase_places
  union all
  select uuid, 'test_places'::text as source_table,
         taihan, tl1, tl2, tl3, tai_note, honzii, hp1, hp2, hp3, h_dialect, hak_note
  from public.test_places
), legacy_fields as (
  select
    c.id as case_id,
    1 as version_no,
    case when c.language = '台語' then jsonb_strip_nulls(jsonb_build_object(
      'TaiHan1', nullif(src.taihan, ''), 'TL1', nullif(src.tl1, ''),
      'TL2', nullif(src.tl2, ''), 'TL3', nullif(src.tl3, ''),
      'TaiNote', nullif(src.tai_note, '')
    )) else jsonb_strip_nulls(jsonb_build_object(
      'Honzii', nullif(src.honzii, ''), 'HP1', nullif(src.hp1, ''),
      'HP2', nullif(src.hp2, ''), 'HP3', nullif(src.hp3, ''),
      'HDialect', nullif(src.h_dialect, ''), 'HakNote', nullif(src.hak_note, '')
    )) end as fields
  from public.annotation_cases c
  join public.final_tasks ft on ft.id = c.task_id
  join source_rows src on src.uuid = ft.source_id and src.source_table = ft.source_table
)
insert into public.annotation_versions (case_id, version_no, version_kind, fields, created_by)
select case_id, version_no, 'legacy', fields, 'legacy_import'
from legacy_fields
where fields <> '{}'::jsonb
on conflict (case_id, version_no) do nothing;

update public.annotation_cases c
set current_version_no = coalesce(v.max_version_no, 0),
    updated_at = now()
from (
  select case_id, max(version_no) as max_version_no
  from public.annotation_versions
  group by case_id
) v
where v.case_id = c.id;

create or replace view public.app_review_workflow_queue as
with source_rows as (
  select uuid, 'third_phase_places'::text as source_table, place_name, type, county, town, village,
         info, tai_class, hak_class, t_updated_at, h_updated_at
  from public.third_phase_places
  union all
  select uuid, 'test_places'::text as source_table, place_name, type, county, town, village,
         info, tai_class, hak_class, t_updated_at, h_updated_at
  from public.test_places
), latest_versions as (
  select distinct on (case_id) case_id, id as version_id, version_no, version_kind, fields, created_by, created_at
  from public.annotation_versions
  order by case_id, version_no desc
), latest_audio_assessments as (
  select distinct on (audio_record_id, assessor_account)
         audio_record_id, assessor_account, respondent_key, decision, reason, created_at
  from public.audio_assessments
  order by audio_record_id, assessor_account, created_at desc, id desc
), audio_summary as (
  select
    ar.task_id,
    ar.language,
    count(*) filter (where ar.unlinked_at is null) as audio_record_count,
    count(la.audio_record_id) as assessed_audio_count,
    count(*) filter (where la.decision = '可用') as usable_audio_count,
    count(*) filter (where la.decision = '不可用') as unusable_audio_count,
    count(*) filter (where la.decision = '待追問') as follow_up_audio_count,
    count(distinct lower(trim(la.respondent_key))) filter (where la.decision = '可用' and nullif(trim(la.respondent_key), '') is not null) as distinct_respondent_count
  from public.audio_records ar
  left join latest_audio_assessments la on la.audio_record_id = ar.id
  where ar.audio_file_id is not null
  group by ar.task_id, ar.language
)
select
  c.id as case_id,
  c.task_id,
  ft.source_id,
  ft.source_table,
  c.language,
  src.place_name,
  src.type,
  src.county,
  src.town,
  src.village,
  src.info,
  case when c.language = '台語' then src.tai_class else src.hak_class end as class_name,
  c.state,
  c.assigned_to,
  c.assigned_by,
  c.assigned_at,
  c.claim_by,
  c.claim_token,
  c.claim_until,
  c.current_version_no,
  lv.version_id,
  lv.version_kind,
  lv.fields as annotation_fields,
  lv.created_by as annotation_created_by,
  lv.created_at as annotation_created_at,
  c.source_stamp,
  c.legacy_unreviewed,
  coalesce(a.audio_record_count, 0)::integer as audio_record_count,
  coalesce(a.assessed_audio_count, 0)::integer as assessed_audio_count,
  coalesce(a.usable_audio_count, 0)::integer as usable_audio_count,
  coalesce(a.unusable_audio_count, 0)::integer as unusable_audio_count,
  coalesce(a.follow_up_audio_count, 0)::integer as follow_up_audio_count,
  coalesce(a.distinct_respondent_count, 0)::integer as distinct_respondent_count,
  (coalesce(a.distinct_respondent_count, 0) >= 2) as audio_gate_passed,
  case when coalesce(a.assessed_audio_count, 0) = 0 then '未審聽'
       when coalesce(a.follow_up_audio_count, 0) > 0 then '待追問'
       else '已判定' end as audio_review_state,
  case when c.language = '台語' then src.t_updated_at else src.h_updated_at end as current_sheet_stamp
from public.annotation_cases c
join public.final_tasks ft on ft.id = c.task_id
left join source_rows src on src.uuid = ft.source_id and src.source_table = ft.source_table
left join latest_versions lv on lv.case_id = c.id
left join audio_summary a on a.task_id = c.task_id and a.language = c.language;

create or replace view public.app_review_workflow_writeback_queue as
select
  w.id as job_id,
  w.case_id,
  w.version_id,
  w.task_id,
  w.source_id,
  w.source_table,
  w.language,
  w.version_no,
  w.source_stamp,
  w.payload,
  w.idempotency_key,
  w.status,
  w.attempt_count,
  w.last_error,
  w.created_at,
  w.updated_at
from public.writeback_jobs w
where w.status in ('queued', 'processing', 'retry');

create or replace function public.workflow_actor_role_(p_actor_account text)
returns text
language sql
security definer
set search_path to 'public'
as $$
  select lower(trim(i.role))
  from public.investigators i
  where lower(trim(i.account)) = lower(trim(p_actor_account))
    and i.is_active = true
  limit 1;
$$;

create or replace function public.get_review_workflow_queue(p_actor_account text)
returns setof public.app_review_workflow_queue
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_role text := public.workflow_actor_role_(p_actor_account);
begin
  if v_role not in ('admin', 'proofreader') then
    raise exception 'proofreader permission required';
  end if;

  return query
  select q.*
  from public.app_review_workflow_queue q
  where v_role = 'admin'
     or q.assigned_to = p_actor_account
     or q.claim_by = p_actor_account
  order by q.updated_at desc nulls last, q.case_id;
end;
$function$;

create or replace function public.assign_review_case(p_case_id bigint, p_assignee text, p_actor_account text)
returns public.annotation_cases
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_role text := public.workflow_actor_role_(p_actor_account);
  v_case public.annotation_cases;
  v_class_name text;
begin
  if v_role <> 'admin' then raise exception 'admin permission required'; end if;
  if nullif(trim(p_assignee), '') is null then raise exception 'assignee is required'; end if;

  select class_name into v_class_name
  from public.app_review_workflow_queue where case_id = p_case_id;
  if not found then raise exception 'review case not found'; end if;

  update public.annotation_cases
  set assigned_to = trim(p_assignee), assigned_by = p_actor_account, assigned_at = now(),
      state = case when v_class_name = '書面標注' then '書面標注中' else '錄音中' end,
      claim_by = null, claim_token = null, claim_until = null, updated_at = now()
  where id = p_case_id
  returning * into v_case;

  insert into public.proofing_events(case_id, action, actor_account, payload)
  values (p_case_id, 'reassign', p_actor_account, jsonb_build_object('assigned_to', trim(p_assignee)));
  return v_case;
end;
$function$;

create or replace function public.claim_review_case(p_case_id bigint, p_actor_account text)
returns public.annotation_cases
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_role text := public.workflow_actor_role_(p_actor_account);
  v_case public.annotation_cases;
begin
  if v_role not in ('admin', 'proofreader') then raise exception 'proofreader permission required'; end if;

  update public.annotation_cases
  set claim_by = p_actor_account, claim_token = gen_random_uuid(), claim_until = now() + interval '30 minutes',
      state = case when state = '待校對' then '校對中' else state end, updated_at = now()
  where id = p_case_id
    and (v_role = 'admin' or assigned_to = p_actor_account)
    and (claim_until is null or claim_until <= now() or claim_by = p_actor_account)
    and state <> '已完成'
  returning * into v_case;
  if not found then raise exception 'case unavailable or already claimed'; end if;

  insert into public.proofing_events(case_id, action, actor_account)
  values (p_case_id, 'claim', p_actor_account);
  return v_case;
end;
$function$;

create or replace function public.release_review_case(p_case_id bigint, p_actor_account text)
returns public.annotation_cases
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_role text := public.workflow_actor_role_(p_actor_account);
  v_case public.annotation_cases;
begin
  if v_role not in ('admin', 'proofreader') then raise exception 'proofreader permission required'; end if;

  update public.annotation_cases
  set claim_by = null, claim_token = null, claim_until = null,
      state = case when current_version_no > 0 then '待校對' else state end,
      updated_at = now()
  where id = p_case_id
    and (v_role = 'admin' or claim_by = p_actor_account)
  returning * into v_case;
  if not found then raise exception 'case is not claimed by actor'; end if;

  insert into public.proofing_events(case_id, action, actor_account)
  values (p_case_id, 'release', p_actor_account);
  return v_case;
end;
$function$;

create or replace function public.save_annotation_version(
  p_case_id bigint, p_actor_account text, p_fields jsonb
)
returns public.annotation_versions
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_role text := public.workflow_actor_role_(p_actor_account);
  v_case public.annotation_cases;
  v_version public.annotation_versions;
  v_next integer;
begin
  if v_role not in ('admin', 'user', 'annotator', 'audio_assessor') then raise exception 'annotation permission required'; end if;
  select * into v_case from public.annotation_cases where id = p_case_id;
  if not found then raise exception 'review case not found'; end if;
  if v_role <> 'admin' and v_case.assigned_to <> p_actor_account then raise exception 'case assignment required'; end if;

  select coalesce(max(version_no), 0) + 1 into v_next
  from public.annotation_versions where case_id = p_case_id;

  insert into public.annotation_versions(case_id, version_no, version_kind, fields, created_by)
  values (p_case_id, v_next, 'draft', coalesce(p_fields, '{}'::jsonb), p_actor_account)
  returning * into v_version;

  update public.annotation_cases
  set current_version_no = v_next,
      state = case when state in ('錄音中', '書面標注中', 'legacy_unreviewed') then '待校對' else state end,
      updated_at = now()
  where id = p_case_id;
  return v_version;
end;
$function$;

create or replace function public.submit_audio_assessment(
  p_task_id integer, p_language text, p_audio_record_id bigint,
  p_assessor_account text, p_respondent_key text, p_decision text, p_reason text default ''
)
returns public.audio_assessments
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_role text := public.workflow_actor_role_(p_assessor_account);
  v_assessment public.audio_assessments;
begin
  if v_role not in ('admin', 'user', 'annotator', 'audio_assessor') or v_role = 'proofreader' then
    raise exception 'audio assessment permission required';
  end if;
  if p_language not in ('台語', '客語') then raise exception 'unsupported language'; end if;
  if p_decision not in ('可用', '不可用', '待追問') then raise exception 'unsupported audio decision'; end if;
  if nullif(trim(p_respondent_key), '') is null then raise exception 'respondent key is required'; end if;

  if not exists (
    select 1 from public.audio_records ar
    where ar.id = p_audio_record_id and ar.task_id = p_task_id and ar.language = p_language and ar.unlinked_at is null
  ) then raise exception 'audio record not found or unlinked'; end if;

  insert into public.audio_assessments(task_id, language, audio_record_id, assessor_account, respondent_key, decision, reason)
  values (p_task_id, p_language, p_audio_record_id, p_assessor_account, trim(p_respondent_key), p_decision, coalesce(p_reason, ''))
  returning * into v_assessment;
  return v_assessment;
end;
$function$;

create or replace function public.approve_review_case(p_case_id bigint, p_actor_account text)
returns public.writeback_jobs
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_role text := public.workflow_actor_role_(p_actor_account);
  q record;
  v_job public.writeback_jobs;
  v_key text;
  v_stamp text;
begin
  if v_role not in ('admin', 'proofreader') then raise exception 'proofreader permission required'; end if;
  select * into q from public.app_review_workflow_queue where case_id = p_case_id;
  if not found then raise exception 'review case not found'; end if;
  if v_role <> 'admin' and (q.claim_by <> p_actor_account or q.claim_until is null or q.claim_until <= now()) then
    raise exception 'active proofreader claim required';
  end if;
  if q.version_id is null or coalesce(q.annotation_fields, '{}'::jsonb) = '{}'::jsonb then
    raise exception 'annotation draft is required';
  end if;
  if not q.audio_gate_passed then raise exception 'two different respondents with usable audio are required'; end if;

  v_stamp := coalesce(q.current_sheet_stamp, '');
  v_key := q.case_id::text || ':' || q.current_version_no::text || ':' || coalesce(v_stamp, 'no-source-stamp');

  update public.annotation_cases
  set state = '已完成', updated_at = now()
  where id = p_case_id;

  insert into public.proofing_events(case_id, action, actor_account, payload)
  values (p_case_id, 'approve', p_actor_account, jsonb_build_object(
    'version_id', q.version_id, 'version_no', q.current_version_no,
    'audio_gate_passed', q.audio_gate_passed
  ));

  insert into public.writeback_jobs(
    case_id, version_id, task_id, source_id, source_table, language,
    version_no, source_stamp, payload, idempotency_key
  ) values (
    q.case_id, q.version_id, q.task_id, q.source_id, q.source_table, q.language,
    q.current_version_no, v_stamp, q.annotation_fields, v_key
  ) on conflict (idempotency_key) do update set updated_at = now()
  returning * into v_job;
  return v_job;
end;
$function$;

create or replace function public.complete_review_writeback(p_job_id bigint, p_source_stamp text)
returns boolean
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  update public.writeback_jobs
  set status = 'succeeded', completed_at = now(), updated_at = now(), last_error = ''
  where id = p_job_id
    and source_stamp = coalesce(p_source_stamp, '')
    and status in ('queued', 'processing', 'retry');
  return found;
end;
$function$;

create or replace function public.fail_review_writeback(
  p_job_id bigint, p_error_code text, p_error_message text, p_details jsonb default '{}'::jsonb
)
returns boolean
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_case_id bigint;
  v_attempts integer;
begin
  select case_id, attempt_count into v_case_id, v_attempts
  from public.writeback_jobs where id = p_job_id for update;
  if not found then return false; end if;

  update public.writeback_jobs
  set attempt_count = attempt_count + 1,
      status = case when attempt_count + 1 >= 5 then 'failed' else 'retry' end,
      last_error = coalesce(p_error_message, ''), updated_at = now()
  where id = p_job_id;

  insert into public.writeback_errors(job_id, case_id, error_code, error_message, details)
  values (p_job_id, v_case_id, coalesce(p_error_code, 'unknown'), coalesce(p_error_message, ''), coalesce(p_details, '{}'::jsonb));
  return true;
end;
$function$;

revoke all on public.annotation_cases, public.annotation_versions, public.audio_assessments,
  public.proofing_events, public.writeback_jobs, public.writeback_errors
  from anon, authenticated;

revoke all on function public.workflow_actor_role_(text) from public, anon, authenticated;
revoke all on function public.complete_review_writeback(bigint, text) from public, anon, authenticated;
revoke all on function public.fail_review_writeback(bigint, text, text, jsonb) from public, anon, authenticated;
grant execute on function public.get_review_workflow_queue(text) to anon, authenticated;
grant execute on function public.assign_review_case(bigint, text, text) to anon, authenticated;
grant execute on function public.claim_review_case(bigint, text) to anon, authenticated;
grant execute on function public.release_review_case(bigint, text) to anon, authenticated;
grant execute on function public.save_annotation_version(bigint, text, jsonb) to anon, authenticated;
grant execute on function public.submit_audio_assessment(integer, text, bigint, text, text, text, text) to anon, authenticated;
grant execute on function public.approve_review_case(bigint, text) to anon, authenticated;
grant execute on function public.complete_review_writeback(bigint, text) to service_role;
grant execute on function public.fail_review_writeback(bigint, text, text, jsonb) to service_role;
grant select on public.app_review_workflow_writeback_queue to service_role;
